name: notebook_web
description: "A new Flutter project."
publish_to: 'none'
version: 2.5.5

environment:
  sdk: ^3.5.2

dependencies:
  dart_frog: ^1.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  responsive_framework: ^1.5.1
  url_launcher: ^6.1.7
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Afacad_Flux
      fonts:
        - asset: assets/fonts/Afacad_Flux/static/AfacadFlux-Black.ttf
          weight: 900
        - asset: assets/fonts/Afacad_Flux/static/AfacadFlux-Bold.ttf
          weight: 700
        - asset: assets/fonts/Afacad_Flux/static/AfacadFlux-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Afacad_Flux/static/AfacadFlux-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Afacad_Flux/static/AfacadFlux-Light.ttf
          weight: 300
        - asset: assets/fonts/Afacad_Flux/static/AfacadFlux-Medium.ttf
          weight: 500
        - asset: assets/fonts/Afacad_Flux/static/AfacadFlux-Regular.ttf
          weight: 400
        - asset: assets/fonts/Afacad_Flux/static/AfacadFlux-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Afacad_Flux/static/AfacadFlux-Thin.ttf
          weight: 100

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
    
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-ThinItalic.ttf
          weight: 100
          style: italic
        
        
        
      
